spring:
  application:
    name: file-service # ==> This is Service-Id
  resources:
    add-mappings: false

eureka:
  instance:
    appname: file-service  # ==> This is a instance of quantum-service
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8781
