spring:
  application:
    name: gateway-service # ==> This is Service-Id
  resources:
    add-mappings: false
  cloud:
    gateway:
      routes:
        - id: quantum-service
          uri: http://localhost:8780/
          predicates:
            - Path=/quantum/**
        - id: file-service
          uri: http://localhost:8781/
          predicates:
            - Path=/file/**

eureka:
  instance:
    appname: gateway-service  # ==> This is a instance of quantum-service
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080
